from pathlib import Path

p = Path("vignettes/an_introduction_to_markovchain_package.Rmd")
s = p.read_text(encoding="utf-8")
old = '''The transition matrix of a `markovchain` object can be displayed using `print` or `show` methods (the latter being less verbose). Similarly, the underlying transition probability diagram can be plotted by the use of `plot` method (as shown in Figure \\@ref(fig:mcPlot)) which is based on \\pkg{igraph} package [@pkg:igraph].\n\n### ggplot2-based plotting\n\nAs an alternative to the standard `plot` method, the package also provides an `autoplot` method based on `ggplot2`. The method returns a regular `ggplot` object, so the resulting graph can be further customised using the grammar of graphics. States are represented as nodes, transition probabilities as directed edges, and communicating classes are shown with different node fills. By default, only transitions with positive probability are displayed and their probabilities are labelled on the edges.\n\nThe method is available when the optional `ggplot2` package is installed:\n\n```{r mcAutoplot, eval=FALSE}\nggplot2::autoplot(mcWeather)\n```\n\nThe returned object can be customised like any other `ggplot` object. For example, transition labels can be hidden and very small probabilities can be omitted:\n\n```{r mcAutoplotCustom, eval=FALSE}\nggplot2::autoplot(mcWeather,\n                  show_probabilities = FALSE,\n                  threshold = 0.2)\n```\n`plot` method for `markovchain` objects is a wrapper of `plot.igraph` for `igraph` S4 objects defined within the \\pkg{igraph} package. Additional parameters can be passed to `plot` function to control the network graph layout. There are also \\pkg{diagram} and \\pkg{DiagrammeR} ways available for plotting as shown in Figure \\@ref(fig:mcPlotdiagram). The `plot` function also uses `communicatingClasses` function to separate out states of different communicating classes. All states that belong to one class have same color.'''
new = '''The transition matrix of a `markovchain` object can be displayed using `print` or `show` methods (the latter being less verbose). Similarly, the underlying transition probability diagram can be plotted by the use of `plot` method (as shown in Figure \\@ref(fig:mcPlot)) which is based on \\pkg{igraph} package [@pkg:igraph]. The standard `plot` method remains the default plotting approach in the package and provides direct access to the underlying `igraph` representation.\n\n### Alternative ggplot2-based plotting\n\nFor users who prefer the grammar of graphics, the package also provides an optional `autoplot` method based on \\pkg{ggplot2}. This is a **supplementary alternative** to `plot`, not a replacement. The method returns a regular `ggplot` object, allowing the Markov chain representation to be further customised with the usual `ggplot2` layers and scales. States are represented as nodes, transition probabilities as directed edges, and communicating classes are shown with different node fills.\n\nThe two approaches can be compared directly using the same `mcWeather` object. The left panel uses the traditional `plot` method, while the right panel uses `ggplot2::autoplot`:\n\n```{r mcPlotComparison, fig.cap="The same Markov chain represented with the traditional `plot` method (left) and the optional `ggplot2`-based `autoplot` method (right).", fig.width=12, fig.height=5}\nif (requireNamespace("ggplot2", quietly = TRUE)) {\n  old_par <- par(mfrow = c(1, 2), mar = c(1, 1, 3, 1))\n  plot(mcWeather, main = "Traditional plot()")\n  print(ggplot2::autoplot(mcWeather) +\n          ggplot2::labs(title = "ggplot2::autoplot()"))\n  par(old_par)\n}\n```\n\nThe `autoplot` method is available when the optional `ggplot2` package is installed. By default, transitions with positive probability are displayed and labelled with their probabilities. The `threshold` argument can be used to omit very small transition probabilities, while `show_probabilities = FALSE` suppresses edge labels. For example:\n\n```{r mcAutoplotCustom, eval=FALSE}\nggplot2::autoplot(mcWeather,\n                  show_probabilities = FALSE,\n                  threshold = 0.2)\n```\n\nThe existing `plot` method for `markovchain` objects is a wrapper of `plot.igraph` for `igraph` S4 objects defined within the \\pkg{igraph} package. Additional parameters can be passed to `plot` function to control the network graph layout. There are also \\pkg{diagram} and \\pkg{DiagrammeR} ways available for plotting as shown in Figure \\@ref(fig:mcPlotdiagram). The `plot` function also uses `communicatingClasses` function to separate out states of different communicating classes. All states that belong to one class have same color.'''
if old not in s:
    raise SystemExit("target section not found")
p.write_text(s.replace(old, new, 1), encoding="utf-8")
Path(".github/workflows/update-autoplot-vignette.yml").unlink()
Path(".github/scripts/update_autoplot_vignette.py").unlink()
