# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createSequenceMatrix_cpp <- function(stringchar, toRowProbs = FALSE, sanitize = TRUE) {
    .Call('markovchain_createSequenceMatrix_cpp', PACKAGE = 'markovchain', stringchar, toRowProbs, sanitize)
}

markovchainFit_cpp <- function(data, method = "mle", byrow = TRUE, nboot = 10L, laplacian = 0, name = "", parallel = FALSE, confidencelevel = 0.95) {
    .Call('markovchain_markovchainFit_cpp', PACKAGE = 'markovchain', data, method, byrow, nboot, laplacian, name, parallel, confidencelevel)
}

